# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /PPM

# Copy the current directory contents into the container at /app
COPY PPM2 .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variable for Django settings module
ENV DJANGO_SETTINGS_MODULE=PPM.settings

# Expose port 8000 for the Django app
EXPOSE 8000

# Run the application with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "PPM.wsgi:application"]
